# Generated by Django 2.2.4 on 2019-10-15 07:38

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('areaid', models.CharField(max_length=10)),
                ('areaName', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='quality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quality', models.FloatField(default=0.0)),
                ('time', models.DateTimeField(default=datetime.datetime(2019, 10, 15, 7, 38, 30, 540262, tzinfo=utc))),
            ],
        ),
        migrations.CreateModel(
            name='userConsumption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consumption', models.FloatField(default=0.0)),
                ('time', models.DateTimeField(default=datetime.datetime(2019, 10, 15, 7, 38, 30, 540647, tzinfo=utc))),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='houseDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house_no', models.CharField(max_length=256, unique=True)),
                ('street_name', models.CharField(max_length=256)),
                ('pincode', models.IntegerField()),
                ('time', models.DateTimeField(default=datetime.datetime(2019, 10, 15, 7, 38, 30, 539187, tzinfo=utc))),
                ('Area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.area')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Complain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complain', models.CharField(max_length=256)),
                ('time', models.DateTimeField(default=datetime.datetime(2019, 10, 15, 7, 38, 30, 541226, tzinfo=utc))),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='areaQuantity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField(default=0.0)),
                ('time', models.DateTimeField(default=datetime.datetime(2019, 10, 15, 7, 38, 30, 539818, tzinfo=utc))),
                ('areaN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.area')),
            ],
        ),
    ]
