# Generated by Django 2.2.1 on 2019-10-16 16:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20191016_1012'),
    ]

    operations = [
        migrations.AddField(
            model_name='userconsumption',
            name='areaid',
            field=models.CharField(default='AREA1', max_length=256),
        ),
        migrations.AlterField(
            model_name='areaquantity',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 16, 16, 11, 28, 956341, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='complain',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 16, 16, 11, 28, 957677, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='housedetails',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 16, 16, 11, 28, 955563, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='quality',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 16, 16, 11, 28, 956785, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='userconsumption',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 16, 16, 11, 28, 957191, tzinfo=utc)),
        ),
    ]
