# Generated by Django 2.2.1 on 2019-10-31 20:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20191031_2030'),
    ]

    operations = [
        migrations.AddField(
            model_name='tax',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 31, 20, 40, 0, 853768, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='areaquantity',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 31, 20, 40, 0, 851749, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='complain',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 31, 20, 40, 0, 853156, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='housedetails',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 31, 20, 40, 0, 851076, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='quality',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 31, 20, 40, 0, 852200, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='userconsumption',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 31, 20, 40, 0, 852613, tzinfo=utc)),
        ),
    ]
