# Generated by Django 2.2.1 on 2019-11-03 12:21

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20191101_0450'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quality',
            old_name='quality',
            new_name='voltage',
        ),
        migrations.AlterField(
            model_name='areaquantity',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 3, 12, 21, 43, 767634, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='complain',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 3, 12, 21, 43, 772578, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='housedetails',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 3, 12, 21, 43, 765639, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='quality',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 3, 12, 21, 43, 769008, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='tax',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 3, 12, 21, 43, 774288, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='userconsumption',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 3, 12, 21, 43, 770731, tzinfo=utc)),
        ),
    ]
