# Generated by Django 2.2.1 on 2019-11-05 15:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_auto_20191105_1554'),
    ]

    operations = [
        migrations.AddField(
            model_name='quality',
            name='ntu',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='areaquantity',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 5, 15, 55, 49, 700985, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='complain',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 5, 15, 55, 49, 702387, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='housedetails',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 5, 15, 55, 49, 700283, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='quality',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 5, 15, 55, 49, 701440, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='tax',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 5, 15, 55, 49, 702981, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='userconsumption',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 5, 15, 55, 49, 701875, tzinfo=utc)),
        ),
    ]
